### ISSUE TITLE
Is this project being developed or abandoned?

### ISSUE THREAD

**Issue by dashesy** [Friz-zy/pyspaces#9]
This would be a great option to run unsafe code. Using python to run basic tasks in LLM-based architectures is becoming very popular. This requires running code generated by LLMs.
While we could use actual docker container and marshal data between them, pyspaces look like a much better solution to create containers on the fly (basic namespaces) and run a code there.

**Comment by Friz-zy** [comment]
Hey) This project is abandoned and I recommend you to look at the finished sandboxes here: https://github.com/Friz-zy/awesome-linux-containers#sandboxes

You can also use OCI runtimes like crun for start container from your own rootfs. Podman should have this option too I think.

And finally, you can just mount data into containers without copying...
